"""Seed the database with initial domains and datasets."""
from sqlalchemy.orm import Session

from app.models.dataset import Dataset
from app.models.domain import Domain

DOMAINS = [
    {"name": "Finance", "slug": "finance", "description": "Financial time-series and tabular data"},
    {"name": "Aviation", "slug": "aviation", "description": "Aviation telemetry and flight data"},
    {"name": "Healthcare", "slug": "healthcare", "description": "FHIR-compatible synthetic patient records"},
]

DATASETS = [
    {
        "name": "Synthetic Stock Prices (S&P 500 style)",
        "description": "1,000 rows of OHLCV synthetic daily stock price data modelled on large-cap equities.",
        "domain_slug": "finance",
        "storage_path": "seed/finance/synthetic_stock_prices.csv",
        "row_count": 1000,
        "column_count": 6,
        "credit_cost": 1,
    },
    {
        "name": "Synthetic Flight Telemetry",
        "description": "10,000 rows of altitude, speed, and heading time-series generated by TimeGAN.",
        "domain_slug": "aviation",
        "storage_path": "seed/aviation/synthetic_flight_telemetry.csv",
        "row_count": 10000,
        "column_count": 8,
        "credit_cost": 2,
    },
    {
        "name": "Synthetic Patient Records (FHIR)",
        "description": "5,000 synthetic patient records with demographics, diagnoses, and lab values.",
        "domain_slug": "healthcare",
        "storage_path": "seed/healthcare/synthetic_patient_records.csv",
        "row_count": 5000,
        "column_count": 20,
        "credit_cost": 3,
    },
]


def run_seed(db: Session) -> None:
    """Idempotently seed domains and datasets."""
    slug_to_domain: dict[str, Domain] = {}

    for d in DOMAINS:
        existing = db.query(Domain).filter(Domain.slug == d["slug"]).first()
        if not existing:
            domain = Domain(**d)
            db.add(domain)
            db.flush()
            slug_to_domain[d["slug"]] = domain
        else:
            slug_to_domain[d["slug"]] = existing

    for ds in DATASETS:
        domain = slug_to_domain[ds["domain_slug"]]
        existing = db.query(Dataset).filter(
            Dataset.storage_path == ds["storage_path"]
        ).first()
        if not existing:
            dataset = Dataset(
                name=ds["name"],
                description=ds["description"],
                domain_id=domain.id,
                storage_path=ds["storage_path"],
                row_count=ds["row_count"],
                column_count=ds["column_count"],
                credit_cost=ds["credit_cost"],
            )
            db.add(dataset)

    db.commit()
